package com.rowi.lms.modle.transaction;


import java.util.Date;

/**
 * AccountTrans generated by Roshan
 */
public class AccountTrans  implements java.io.Serializable {


     private Integer indexNo;
     private Date transactionDate;
     private String costCode;
     private String accountSetting;
     private String description;
     private String account;
     private double creditAmount;
     private double debitAmount;
     private int transaction;
     private String transactionType;
     private String type;
     private String status;
     private Date dateTime;
     private String user;

    public AccountTrans() {
    }

	
    public AccountTrans(Date transactionDate, String costCode, String account, double creditAmount, double debitAmount, int transaction, String transactionType, String type, String status, Date dateTime, String user) {
        this.transactionDate = transactionDate;
        this.costCode = costCode;
        this.account = account;
        this.creditAmount = creditAmount;
        this.debitAmount = debitAmount;
        this.transaction = transaction;
        this.transactionType = transactionType;
        this.type = type;
        this.status = status;
        this.dateTime = dateTime;
        this.user = user;
    }
    public AccountTrans(Date transactionDate, String costCode, String accountSetting, String description, String account, double creditAmount, double debitAmount, int transaction, String transactionType, String type, String status, Date dateTime, String user) {
       this.transactionDate = transactionDate;
       this.costCode = costCode;
       this.accountSetting = accountSetting;
       this.description = description;
       this.account = account;
       this.creditAmount = creditAmount;
       this.debitAmount = debitAmount;
       this.transaction = transaction;
       this.transactionType = transactionType;
       this.type = type;
       this.status = status;
       this.dateTime = dateTime;
       this.user = user;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getCostCode() {
        return this.costCode;
    }
    
    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }
    public String getAccountSetting() {
        return this.accountSetting;
    }
    
    public void setAccountSetting(String accountSetting) {
        this.accountSetting = accountSetting;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public double getCreditAmount() {
        return this.creditAmount;
    }
    
    public void setCreditAmount(double creditAmount) {
        this.creditAmount = creditAmount;
    }
    public double getDebitAmount() {
        return this.debitAmount;
    }
    
    public void setDebitAmount(double debitAmount) {
        this.debitAmount = debitAmount;
    }
    public int getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(int transaction) {
        this.transaction = transaction;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }




}


