package com.rowi.lms.modle.transaction;
// Generated Dec 8, 2015 7:48:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer indexNo;
     private Date transactionDate;
     private String costCode;
     private String customer;
     private Integer cashireSession;
     private double amount;
     private int transaction;
     private String transactionType;
     private String status;
     private String user;
     private Date dateTime;
     private Set<PaymentInformation> paymentInformations = new HashSet<PaymentInformation>(0);

    public Payment() {
    }

	
    public Payment(Date transactionDate, String costCode, double amount, int transaction, String transactionType, String status, String user, Date dateTime) {
        this.transactionDate = transactionDate;
        this.costCode = costCode;
        this.amount = amount;
        this.transaction = transaction;
        this.transactionType = transactionType;
        this.status = status;
        this.user = user;
        this.dateTime = dateTime;
    }
    public Payment(Date transactionDate, String costCode, String customer, Integer cashireSession, double amount, int transaction, String transactionType, String status, String user, Date dateTime, Set<PaymentInformation> paymentInformations) {
       this.transactionDate = transactionDate;
       this.costCode = costCode;
       this.customer = customer;
       this.cashireSession = cashireSession;
       this.amount = amount;
       this.transaction = transaction;
       this.transactionType = transactionType;
       this.status = status;
       this.user = user;
       this.dateTime = dateTime;
       this.paymentInformations = paymentInformations;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getCostCode() {
        return this.costCode;
    }
    
    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }
    public Integer getCashireSession() {
        return this.cashireSession;
    }
    
    public void setCashireSession(Integer cashireSession) {
        this.cashireSession = cashireSession;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public int getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(int transaction) {
        this.transaction = transaction;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set<PaymentInformation> getPaymentInformations() {
        return this.paymentInformations;
    }
    
    public void setPaymentInformations(Set<PaymentInformation> paymentInformations) {
        this.paymentInformations = paymentInformations;
    }




}


