package com.rowi.lms.modle.transaction;


/**
 * PaymentInformation generated by Roshan
 */
public class PaymentInformation  implements java.io.Serializable {


     private Integer indexNo;
     private Payment payment;
     private String paymentSetting;
     private double amount;
     private int transaction;
     private String transactionType;
     private String refaranceNo;

    public PaymentInformation() {
    }

	
    public PaymentInformation(Payment payment, String paymentSetting, double amount, int transaction, String transactionType) {
        this.payment = payment;
        this.paymentSetting = paymentSetting;
        this.amount = amount;
        this.transaction = transaction;
        this.transactionType = transactionType;
    }
    public PaymentInformation(Payment payment, String paymentSetting, double amount, int transaction, String transactionType, String refaranceNo) {
       this.payment = payment;
       this.paymentSetting = paymentSetting;
       this.amount = amount;
       this.transaction = transaction;
       this.transactionType = transactionType;
       this.refaranceNo = refaranceNo;
    }
   
    public Integer getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }
    public String getPaymentSetting() {
        return this.paymentSetting;
    }
    
    public void setPaymentSetting(String paymentSetting) {
        this.paymentSetting = paymentSetting;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public int getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(int transaction) {
        this.transaction = transaction;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public String getRefaranceNo() {
        return this.refaranceNo;
    }
    
    public void setRefaranceNo(String refaranceNo) {
        this.refaranceNo = refaranceNo;
    }




}


