package com.rowi.lms.modle.transaction;

import java.util.Date;

/**
 * TransactionHistory generated by Roshan
 */
public class TransactionHistory implements java.io.Serializable {

    private Integer indexNo;
    private Transaction transaction;
    private String action;
    private String user;
    private String note;

    public TransactionHistory() {
    }

    public TransactionHistory(Transaction transaction, String action, String user) {
        this.transaction = transaction;
        this.action = action;
        this.user = user;
    }

    public TransactionHistory(Transaction transaction, String action, String user, String note) {
        this.transaction = transaction;
        this.action = action;
        this.user = user;
        this.note = note;
    }

    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    public Transaction getTransaction() {
        return this.transaction;
    }

    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
