package com.rowi.lms.modle.transaction;



/**
 * TransactionType generated by Roshan
 */
public class TransactionType  implements java.io.Serializable {


     private String code;
     private String name;

    public TransactionType() {
    }

	
    public TransactionType(String code) {
        this.code = code;
    }
    public TransactionType(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


