package com.rowi.lms.modle.transaction;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by Roshan
 */
public class Transaction implements java.io.Serializable {

    private Integer indexNo;
    private Date transactionDate;
    private String transactionType;
    private String referanceNo;
    private String documentNo;
    private String loan;
    private String costCode;
    private String customer;
    private String note;
    private String status;
    private String user;
    private Date dateTime;
    private Set<TransactionHistory> transactionHistories = new HashSet<TransactionHistory>(0);

    public Transaction() {
    }

    public Transaction(Date transactionDate, String transactionType, String referanceNo, String costCode, String status, String user, Date dateTime) {
        this.transactionDate = transactionDate;
        this.transactionType = transactionType;
        this.referanceNo = referanceNo;
        this.costCode = costCode;
        this.status = status;
        this.user = user;
        this.dateTime = dateTime;
    }

    public Transaction(Date transactionDate, String transactionType, String referanceNo, String documentNo, String loan, String costCode, String custCode, String note, String status, String user, Date dateTime, Set<TransactionHistory> transactionHistories) {
        this.transactionDate = transactionDate;
        this.transactionType = transactionType;
        this.referanceNo = referanceNo;
        this.documentNo = documentNo;
        this.loan = loan;
        this.costCode = costCode;
        this.customer = custCode;
        this.note = note;
        this.status = status;
        this.user = user;
        this.dateTime = dateTime;
        this.transactionHistories = transactionHistories;
    }

    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    public Date getTransactionDate() {
        return this.transactionDate;
    }

    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    public String getTransactionType() {
        return this.transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public String getReferanceNo() {
        return this.referanceNo;
    }

    public void setReferanceNo(String referanceNo) {
        this.referanceNo = referanceNo;
    }

    public String getDocumentNo() {
        return this.documentNo;
    }

    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    public String getLoan() {
        return this.loan;
    }

    public void setLoan(String loan) {
        this.loan = loan;
    }

    public String getCostCode() {
        return this.costCode;
    }

    public void setCostCode(String costCode) {
        this.costCode = costCode;
    }

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String custCode) {
        this.customer = custCode;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Date getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    public Set<TransactionHistory> getTransactionHistories() {
        return this.transactionHistories;
    }

    public void setTransactionHistories(Set<TransactionHistory> transactionHistories) {
        this.transactionHistories = transactionHistories;
    }

}
